### ISSUE TITLE
property 'activeScenes' of undefined

### ISSUE THREAD

**Issue by Gatech0** [aloeguvner/rpg-maker-mv#1]
Hello. 

I just downloaded this plugin and setup d-pad Image, and set everything as default. When loading the game, get 

TypeError: Cannot read property 'activeScenes' of undefined
    at Scene_Boot.create (/E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/PAD.js:798)
    at Function.SceneManager.changeScene (rpg_managers.js:1654)
    at Function.SceneManager.updateMain (rpg_managers.js:1640)
    at Function.SceneManager.update (rpg_managers.js:1576)

D-pad settings: {"image":"DirPad","activeScenes":"[\"Scene_Title\",\"Scene_Map\"]","x":"20","y":"Graphics.height - 96","soundEffect":""}

MV 1.5.0.
Please help, thank you.

**Comment by aloeguvner** [comment]
This is because the parameters of the plugin are not being read. Please ensure to not rename the file, instead, keep the name of the plugin exactly the same as on here. (ALOE_MobileUI.js)

**Comment by aloeguvner** [comment]
The easiest way to download an individual file from Github is to right-click on the "Raw" button and select "Save link as..."
![githupdownload](https://user-images.githubusercontent.com/39887666/45458298-fb3f3600-b6c0-11e8-901d-f3c7823cc176.png)

**Comment by Gatech0** [comment]
So sorry about that mistake. Now fixed.

Buttons set up and show in the screen, but when clicked on screen:

TypeError: undefined is not a function
    at Sprite_DirectionalPad.updateTouchInput (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/ALOE_MobileUI.js:577:13)
    at Sprite_DirectionalPad.Sprite_Button.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/ALOE_MobileUI.js:476:9)
    at file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/rpg_scenes.js:112:19
    at Array.forEach (native)
    at Scene_Title.Scene_Base.updateChildren (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/rpg_scenes.js:110:19)
    at Scene_Title.Scene_Base.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/rpg_scenes.js:42:10)
    at Scene_Title.Scene_Base.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/YEP_ExternalLinks.js:181:35)
    at Scene_Title.Scene_Base.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/MOG_MenuCursor.js:91:33)
    at Scene_Title.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/rpg_scenes.js:265:33)
    at Scene_Title.update (file:///E:/Mis%20Documentos/Dropbox/Calg%20Nuevo/js/plugins/MOG_TitleParticles.js:122:39)

**Comment by aloeguvner** [comment]
I'm sorry, I am not able to recreate the issue.

Can you please share the following?
1. The version of your RPG Maker program. (Press Help --> About... )
2. The version of your project files (open rpg_core.js in any text editor and read the first few lines)
3. A screenshot of all relevant parameters you've configured for the plugin
4. A screenshot of the full error message from the console

The error message indicates that the method "containsPoint" is undefined, however, this method comes from PIXI, so I can't understand how it could be undefined for any child class of PIXI.Sprite

It works fine when I test it, see screenshot below.
(I can use the D-Pad to navigate the menu and the "A" button to start a New Game.)
![mobileuitest](https://user-images.githubusercontent.com/39887666/45498967-53217f80-b749-11e8-8ed7-9775a7e642df.png)

**Comment by Gatech0** [comment]
Sorry about all, please close the issue. All the problem was mine with
obsolete project files :@

Now testing, will tell you later.

**Comment by Gatech0** [comment]
I want to disable screen touch on Menus when this D-Pad is shown.
How to do it? Thanks a lot.

**Comment by aloeguvner** [comment]
Ok, I'm glad that you got it working.

For disabling other touch while in menus, this plugin doesn't have that ability yet. I opened #2 for that capability, and will update when it is complete.

**Comment by Alexander869** [comment]
Hello
I downloaded the plugin and it says "I cannot read the undefined 'activeScenes'" why is this error code?
Please help.

**Comment by aloeguvner** [comment]
Hi @Alexander869 ,

I'm not active in RPG Maker anymore but I can try to help from here. Can you please open a new Issue with the full error message?

Please use the template I set up for bug report by clicking this link:
https://github.com/aloeguvner/rpg-maker-mv/issues/new?assignees=&labels=&template=bug_report.md
